name: Udemy course entroller

on:
  push:
    branches: [ "main" ]
    
  schedule:
    - cron: '*/60 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installing Requirements
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Restoring the Cache
        uses: actions/cache@v3
        with:
          path: encrypted_session.txt
          key: session-cache-key

      - name: Running Script  
        env:
          SECURE_KEY: ${{secrets.SECURE_KEY}}
          
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}

          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          SESSION_ID: ${{secrets.SESSION_ID}}
          MYACCESSTOKENS: ${{secrets.MYACCESSTOKENS}}
        run: |
          python UdemyEnroller24.py

      - name: Caching the File
        uses: actions/cache@v3
        with:
          path: encrypted_session.txt
          key: session-cache-key


